/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package book.catalog;

import java.io.IOException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) throws IOException {
        String catalogPath = "src/main/resources/books.json";
        Scanner scanner = new Scanner(System.in);
        Catalog catalog = new Catalog(catalogPath);

        boolean exit = false;
        while (!exit) {
            System.out.println("Enter the number of the operation you want to perform:");
            System.out.println("1. Add a book");
            System.out.println("2. Remove a book");
            System.out.println("3. Edit a book");
            System.out.println("4. Search for a book by title");
            System.out.println("5. Search for a book by author");
            System.out.println("6. Search for a book by genre");
            System.out.println("7. Display all books");
            System.out.println("0. Exit");
            
            int choice = scanner.nextInt();
            scanner.nextLine();
            
            switch (choice) {
                case 0:
                    exit = true;
                    break;
                case 1:
                    catalog.addBook(scanner);
                    break;
                case 2:
                    catalog.removeBook(scanner);
                    break;
                case 3:
                    catalog.editBook(scanner);
                    break;
                case 4:
                    catalog.searchByTitle(scanner);
                    break;
                case 5:
                    catalog.searchByAuthor(scanner);
                    break;
                case 6:
                    catalog.searchByGenre(scanner);
                    break;
                case 7:
                    catalog.displayBooks(catalog.books);
                    break;
                default:
                    System.out.println("Invalid input.");
                    break;
            }
        }
            
        scanner.close();
    }
}